version: '3.4'
services:
  dataprocessor:
    image: sergiopereo/dataprocessor
    container_name: dataprocessor
    ports:
      - 8888:8888
  scylla:
    image: scylladb/scylla
    container_name: scylla
    ports:
      - 9042:9042
    command: --smp 1 --memory 4G
  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none